name: Send Email via Yandex SMTP

on:
  repository_dispatch:
    types: [send-email]

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📧 Send Email via Yandex SMTP
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.ru
        server_port: 587
        username: wish.online@yandex.kz
        password: ${{ secrets.YANDEX_APP_PASSWORD }}
        subject: ${{ github.event.client_payload.subject }}
        to: aleksey@vorobey444.ru
        from: Anonimka.Online <wish.online@yandex.kz>
        reply_to: ${{ github.event.client_payload.email }}
        html_body: |
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
                  .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                  .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px 10px 0 0; }
                  .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; }
                  .message { background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #667eea; }
                  .info { color: #666; font-size: 14px; margin-top: 20px; }
                  .footer { text-align: center; color: #999; font-size: 12px; margin-top: 30px; }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h2>🌟 Новое сообщение с anonimka.online</h2>
                  </div>
                  <div class="content">
                      <div class="info">
                          <strong>От:</strong> ${{ github.event.client_payload.email }}<br>
                          <strong>Тема:</strong> ${{ github.event.client_payload.subject }}<br>
                          <strong>Время:</strong> $(date)<br>
                      </div>
                      <div class="message">
                          <strong>Сообщение:</strong><br><br>
                          ${{ github.event.client_payload.message }}
                      </div>
                      <div class="footer">
                          Письмо отправлено с сайта <strong>anonimka.online</strong><br>
                          Для ответа используйте адрес: <strong>${{ github.event.client_payload.email }}</strong>
                      </div>
                  </div>
              </div>
          </body>
          </html>
        body: |
          Новое сообщение с сайта anonimka.online
          
          От: ${{ github.event.client_payload.email }}
          Тема: ${{ github.event.client_payload.subject }}
          Время: $(date)
          
          Сообщение:
          ${{ github.event.client_payload.message }}
          
          ---
          Это письмо отправлено с сайта anonimka.online
          Для ответа используйте адрес: ${{ github.event.client_payload.email }}